from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="books.index"),
    path('lab4/', views.index1, name="books.index1"),
    path('lab12/task4/', views.lab12_4, name="books.lab12_4"),
    path('lab12/task3/', views.lab12_3, name="books.lab12_3"),
    path('lab12/task2/', views.lab12_2, name="books.lab12_2"),
    path('lab12/task1/', views.lab12_1, name="books.lab12_1"),
    path('index2/<int:val1>', views.index2, name="books.index2"),
    path('list_books/', views.list_books, name="books.list_books"),
    path('lab10/task3/listimages/', views.listimages, name="books.listimages"),
    path('lab10/task3/addimage/', views.addimage, name="books.addimage"),
    path('lab10/task3/deleteimage/<int:id>', views.deleteimage, name="books.deleteimage"),
    path('lab10/task2/liststudents/', views.liststudents2, name="books.liststudents2"),
    path('lab10/task2/addstudent/', views.addstudent2, name="books.addstudent2"),
    path('lab10/task2/editstudent/<int:id>', views.editstudent2, name="books.editstudent2"),
    path('lab10/task2/deletestudent/<int:id>', views.deletestudent2, name="books.deletestudent2"),
    path('lab10/liststudents/', views.liststudents, name="books.liststudents"),
    path('lab10/addstudent/', views.addstudent, name="books.addstudent"),
    path('lab10/editstudent/<int:id>', views.editstudent, name="books.editstudent"),
    path('lab10/deletestudent/<int:id>', views.deletestudent, name="books.deletestudent"),
    path('lab9_part2/listbooks/', views.lab9_2, name="books.lab9_2"),
    path('lab9_part2/addbook/', views.addb_2, name="books.addb_2"),
    path('lab9_part2/editbook/<int:id>', views.edit_2, name="books.edit_2"),
    path('lab9_part2/deletebook/<int:id>', views.delete_2, name="books.delete_2"),
    path('lab9_part1/listbooks/', views.lab9, name="books.lab9"),
    path('lab9_part1/addbook/', views.addb, name="books.addb"),
    path('lab9_part1/editbook/<int:id>', views.edit, name="books.edit"),
    path('lab9_part1/deletebook/<int:id>', views.delete, name="books.delete"),
    path('lab8/task4/', views.task4, name="books.task4"),
    path('lab8/task7/', views.task7, name="books.task7"),
    path('lab8/task5/', views.task5, name="books.task5"),
    path('lab8/task3/', views.task3, name="books.task3"),
    path('lab8/task2/', views.task2, name="books.task2"),
    path('lab8/task1/', views.task1, name="books.task1"),
    path('simple/query/', views.simple_query, name="books.simple_query"),
    path('complex/query/', views.complex_query, name="books.complex_query"),
    path('html5/listing/', views.listing, name="books.listing"),
    path('search/', views.search, name="books.search"),
    path('html5/tables/', views.tables, name="books.tables"),
    path('html5/text/formatting/', views.formatting, name="books.formatting"),
    path('html5/links/', views.links, name="books.links"),
    path('<int:bookId>/', views.viewbook, name="books.view_one_book"),
    path('aboutus/', views.aboutus, name="books.aboutus"),
    path('<int:bookId>', views.viewbook),
    path('lab3/<int:bookId>', views.viewbook1)
]
